refactor: context로 불러오던 localStorage 관련 함수를 util 함수로 변경
boostcampwm2023/baekjoonrooms pull request #298
Opened 2024-03-22 09:53 UTC by kiuuon

## Description

context 파일에 있던 localStorage를 util 파일로 바꿔주었습니다.

## Changes Made

- client/src/contexts/RoomProvider.tsx / client/src/pages/Room/Chat/Chat.tsx
  - RoomProvider는 localStoage.tsx에서 getItem, setItem을 불러오고, Chat에서는 RoomProvider에서 getItem, setItem 가져왔었는데, Chat에서 한번에 localStorage.tsx에서 getItem, setItem을 불러오도록 수정했습니다.

## Extra Comments

로컬 스토리지를 꼭 따로 함수로 빼야하는지 얘기해보고 싶습니다.

2024-03-25 03:46 UTC, Lukaid-dev approved these changes
LGTM! 드디어 제일 걸리적 거리던게 사라지니 속이 다 시원하군요!

저도 router 관련되어 공부한거 곧 정리하여 올리겠습니다!

2024-03-26 13:48 UTC, glowisn requested changes
roomProvider에서 conflict안나게 저는 이 브랜치 머지 되면 작업하면 될 거 같네요
리뷰사항만 읽어주시고 확인해주세요😀

2024-03-26 13:48 UTC, glowisn commented on client/src/contexts/AuthProvider.tsx
> +    console.log('logout');
console.log는 지우는게 어떨까요?

2024-03-26 13:48 UTC, glowisn commented on client/src/utils/localStorage.ts
> +export { getItem, setItem, removeItem };
다른 파일에서 getItem, setItem을 많이 쓰니 getLocalStroageItem등의 이름으로 바꾸는건 어떤가요? 코드를 읽기 더 편할 거 같아요.

2024-03-27 05:56 UTC, kiuuon commented on client/src/contexts/AuthProvider.tsx
> +    console.log('logout');
지우는 걸 깜빡했네요. 😅

2024-03-27 05:56 UTC, kiuuon commented on client/src/utils/localStorage.ts
> +export { getItem, setItem, removeItem };
좋습니다. 수정해보겠습니다.

2024-03-29 08:34 UTC, glowisn approved these changes
LGTM!

2024-03-30 01:26 UTC, merged